#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const DIST_DIR = path.join(ROOT, 'dist');
const SHARED_CSS = path.join(DIST_DIR, 'shared.css');
const SHARED_JS = path.join(DIST_DIR, 'shared.js');
const SELF_REFERENCES = new Set(['dist/shared.css', 'dist/shared.js']);

function walk(dir) {
  const files = [];
  for (const name of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, name.name);
    if (name.isDirectory()) {
      files.push(...walk(full));
    } else if (name.isFile() && full.endsWith('.html')) {
      files.push(full);
    }
  }
  return files;
}

function extractAssets(html) {
  const css = [];
  const js = [];
  const linkRe = /<link[^>]+rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>/gi;
  const scriptRe = /<script[^>]+src=["']([^"']+)["'][^>]*>\s*<\/script>/gi;
  let m;
  while ((m = linkRe.exec(html))) css.push(m[1]);
  while ((m = scriptRe.exec(html))) js.push(m[1]);
  return { css, js };
}

function isLocal(p) {
  return p && !p.startsWith('http') && !p.startsWith('//') && !p.startsWith('data:');
}

function readIfExists(relPath) {
  const p = path.join(ROOT, relPath);
  if (fs.existsSync(p) && fs.statSync(p).isFile()) return fs.readFileSync(p, 'utf8');
  return null;
}

function writeIfChanged(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (prev !== content) fs.writeFileSync(file, content, 'utf8');
}

function updateHtmlFile(file, sharedCssHref, sharedJsHref, cssToRemoveSet, jsToRemoveSet) {
  let html = fs.readFileSync(file, 'utf8');
  const original = html;
  // remove target link tags
  html = html.replace(/<link[^>]+rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>\s*/gi, (m, href) => {
    if (cssToRemoveSet.has(href)) return '';
    return m;
  });
  // inject shared css in head after <head> tag
  if (sharedCssHref && html.includes('</head>') && !html.includes(sharedCssHref)) {
    html = html.replace(/<head[^>]*>/i, match => `${match}\n  <link rel="stylesheet" href="${sharedCssHref}">`);
  }
  // remove script tags
  html = html.replace(/<script[^>]+src=["']([^"']+)["'][^>]*>\s*<\/script>\s*/gi, (m, src) => {
    if (jsToRemoveSet.has(src)) return '';
    return m;
  });
  // inject shared js before </body>
  if (sharedJsHref && html.includes('</body>') && !html.includes(sharedJsHref)) {
    html = html.replace(/<\/body>/i, `  <script src="${sharedJsHref}"></script>\n</body>`);
  }
  if (html !== original) {
    fs.copyFileSync(file, `${file}.bak`);
    fs.writeFileSync(file, html, 'utf8');
    return true;
  }
  return false;
}

function toSharedHref(file, sharedFile) {
  return path.relative(path.dirname(file), sharedFile).replace(/\\/g, '/');
}

function main() {
  const htmlFiles = walk(ROOT);
  const cssCount = new Map();
  const jsCount = new Map();

  for (const f of htmlFiles) {
    const html = fs.readFileSync(f, 'utf8');
    const { css, js } = extractAssets(html);
    const uniqCss = new Set(css.filter((href) => isLocal(href) && !SELF_REFERENCES.has(href)));
    const uniqJs = new Set(js.filter((href) => isLocal(href) && !SELF_REFERENCES.has(href)));
    uniqCss.forEach(h => cssCount.set(h, (cssCount.get(h) || 0) + 1));
    uniqJs.forEach(h => jsCount.set(h, (jsCount.get(h) || 0) + 1));
  }

  // choose threshold: assets used in more than 6 pages
  const CSS_THRESHOLD = 6;
  const JS_THRESHOLD = 6;

  const sharedCss = Array.from(cssCount.entries()).filter(([k,v]) => v >= CSS_THRESHOLD).map(([k]) => k);
  const sharedJs = Array.from(jsCount.entries()).filter(([k,v]) => v >= JS_THRESHOLD).map(([k]) => k);

  console.log('Found', cssCount.size, 'unique local CSS assets,', jsCount.size, 'unique local JS assets');
  console.log('Shared CSS candidates:', sharedCss);
  console.log('Shared JS candidates:', sharedJs);

  // build shared bundles
  let cssBundle = '/* Shared CSS bundle generated by scripts/dedupe-assets.mjs */\n\n';
  for (const rel of sharedCss) {
    if (SELF_REFERENCES.has(rel)) continue;
    const content = readIfExists(rel);
    if (content == null) {
      console.warn('Missing CSS file', rel, ', skipping');
      continue;
    }
    cssBundle += `/* Source: ${rel} */\n` + content + '\n\n';
  }

  let jsBundle = '// Shared JS bundle generated by scripts/dedupe-assets.mjs\n\n';
  for (const rel of sharedJs) {
    if (SELF_REFERENCES.has(rel)) continue;
    const content = readIfExists(rel);
    if (content == null) {
      console.warn('Missing JS file', rel, ', skipping');
      continue;
    }
    jsBundle += `// Source: ${rel}\n` + content + '\n\n';
  }

  // write bundles
  if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });
  if (sharedCss.length) writeIfChanged(SHARED_CSS, cssBundle);
  if (sharedJs.length) writeIfChanged(SHARED_JS, jsBundle);

  const cssToRemoveSet = new Set(sharedCss);
  const jsToRemoveSet = new Set(sharedJs);

  let modified = 0;
  for (const f of htmlFiles) {
    const sharedCssHref = sharedCss.length ? toSharedHref(f, SHARED_CSS) : null;
    const sharedJsHref = sharedJs.length ? toSharedHref(f, SHARED_JS) : null;
    if (updateHtmlFile(f, sharedCssHref, sharedJsHref, cssToRemoveSet, jsToRemoveSet)) modified++;
  }

  console.log('Wrote bundles:', sharedCss.length ? SHARED_CSS : '(none)', sharedJs.length ? SHARED_JS : '(none)');
  console.log('Updated', modified, 'HTML files');
}

main();
