#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const DIST = path.join(ROOT, 'dist', 'design-tokens.mjs');
const OUT = path.join(ROOT, 'design-tokens.css');

async function loadThemes() {
  if (!fs.existsSync(DIST)) {
    throw new Error(`Built token module not found at ${DIST}`);
  }
  const mod = await import(`file://${DIST}`);
  const THEMES = mod.THEMES || mod.default?.THEMES;
  if (!THEMES) throw new Error('THEMES export not found in built design-tokens module');
  return THEMES;
}

function formatTokensBlock(selector, tokens, extraLines = []) {
  const keys = Object.keys(tokens);
  return `${selector} {\n${extraLines.map(l => `  ${l}`).join('\n')}${extraLines.length ? '\n' : ''}${keys.map(k => `  ${k}: ${tokens[k]};`).join('\n')}\n}\n\n`;
}

function buildCss(themes) {
  const light = themes.light?.tokens || {};

  let out = '/* Design Tokens: generated by scripts/token-sync.mjs */\n\n';
  out += formatTokensBlock(':root', light, ['/* Design Tokens: centralized CSS custom properties and theme fallbacks */', 'color-scheme: light;']);

  // global color-scheme declarations for thematic selectors
  Object.entries(themes).forEach(([name, cfg]) => {
    if (cfg.colorScheme && cfg.colorScheme !== 'light') {
      out += `html[data-theme="${name}"] {\n  color-scheme: ${cfg.colorScheme};\n}\n\n`;
    }
  });

  // theme-specific token overrides
  Object.entries(themes).forEach(([name, cfg]) => {
    if (name === 'light') return;
    const tokens = cfg.tokens || {};
    out += formatTokensBlock(`html[data-theme="${name}"]`, tokens);
  });

  return out;
}

function writeOut(css) {
  fs.writeFileSync(OUT, css, 'utf8');
}

function normalize(s) {
  return s.replace(/\r\n/g, '\n').trim() + '\n';
}

async function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');

  try {
    const themes = await loadThemes();
    const css = buildCss(themes);

    if (check) {
      if (!fs.existsSync(OUT)) {
        console.error('design-tokens.css not found for --check');
        process.exit(2);
      }
      const existing = fs.readFileSync(OUT, 'utf8');
      if (normalize(existing) !== normalize(css)) {
        console.error('Design tokens are out of sync. Run `npm run tokens:sync` to update design-tokens.css');
        console.error('--- generated preview ---');
        console.error(css.slice(0, 800));
        process.exit(2);
      }
      console.log('✅ design-tokens.css is up to date');
      process.exit(0);
    }

    writeOut(css);
    console.log('Wrote', OUT);
  } catch (err) {
    console.error(err && err.message ? err.message : String(err));
    process.exit(3);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
