#!/usr/bin/env node
const { program } = require('commander');
const chalk = require('chalk');
const fs = require('fs-extra');
const path = require('path');
const ora = require('ora');

const REGISTRY_PATH = path.join(__dirname, '..', '..', 'data', 'registry.json');

function loadRegistry() {
  try {
    const data = fs.readFileSync(REGISTRY_PATH, 'utf8');
    return JSON.parse(data).registry;
  } catch (error) {
    console.error(chalk.red('Error: Could not load registry. Make sure you are running this from the UI-Verse directory.'));
    process.exit(1);
  }
}

function findComponent(registry, name) {
  return registry.find(c => c.name.toLowerCase() === name.toLowerCase());
}

async function addComponent(componentName, options) {
  const spinner = ora(`Searching for component: ${componentName}`).start();
  
  const registry = loadRegistry();
  const component = findComponent(registry, componentName);
  
  if (!component) {
    spinner.fail(chalk.red(`Component "${componentName}" not found.`));
    console.log(chalk.yellow('\nAvailable components:'));
    registry.forEach(c => {
      console.log(chalk.cyan(`  - ${c.name}`) + chalk.gray(` (${c.title})`));
    });
    process.exit(1);
  }
  
  spinner.succeed(chalk.green(`Found: ${component.title}`));
  
  const targetDir = options.directory || process.cwd();
  const componentDir = path.join(targetDir, component.name);
  
  const installSpinner = ora(`Installing ${component.name} to ${targetDir}`).start();
  
  try {
    await fs.ensureDir(componentDir);
    
    const baseDir = path.join(__dirname, '..', '..');
    const componentFolder = path.join(baseDir, component.name);
    let filesCopied = false;
    
    if (await fs.pathExists(componentFolder)) {
      const files = await fs.readdir(componentFolder);
      for (const file of files) {
        const ext = path.extname(file).toLowerCase();
        if (['.html', '.css', '.js'].includes(ext)) {
          await fs.copy(
            path.join(componentFolder, file),
            path.join(componentDir, file)
          );
          filesCopied = true;
        }
      }
    }
    
    if (!filesCopied) {
      const fileNames = component.files ? Object.values(component.files) : [];
      for (const fileName of fileNames) {
        const rootFilePath = path.join(baseDir, fileName);
        if (await fs.pathExists(rootFilePath)) {
          await fs.copy(rootFilePath, path.join(componentDir, fileName));
          filesCopied = true;
        }
      }
    }
    
    if (!filesCopied) {
      const snippetsDir = path.join(baseDir, 'data', 'snippets', component.name);
      if (await fs.pathExists(snippetsDir)) {
        const files = await fs.readdir(snippetsDir);
        for (const file of files) {
          await fs.copy(
            path.join(snippetsDir, file),
            path.join(componentDir, file)
          );
          filesCopied = true;
        }
      }
    }
    
    const readmeContent = `# ${component.title}

## Installation

This component was installed using: \`npx uiverse add ${component.name}\`

## Files

${component.files ? Object.keys(component.files).map(k => `- ${component.files[k]}`).join('\n') : 'Component files installed'}

## Description

${component.description}

## Tags

${component.tags.join(', ')}

---
Generated by UI-Verse CLI
`;
    
    await fs.writeFile(path.join(componentDir, 'README.md'), readmeContent);
    
    installSpinner.succeed(chalk.green(`Component "${component.name}" installed successfully!`));
    
    console.log(chalk.blue('\nNext steps:'));
    console.log(chalk.gray(`  cd ${component.name}`));
    console.log(chalk.gray('  # Open the HTML file in your browser'));
    
  } catch (error) {
    installSpinner.fail(chalk.red(`Failed to install component: ${error.message}`));
    process.exit(1);
  }
}

async function listComponents() {
  const spinner = ora('Loading registry...').start();
  const registry = loadRegistry();
  spinner.stop();
  
  console.log(chalk.bold('\n📦 Available UI-Verse Components\n'));
  
  const categories = {};
  registry.forEach(c => {
    if (!categories[c.category]) {
      categories[c.category] = [];
    }
    categories[c.category].push(c);
  });
  
  Object.keys(categories).forEach(cat => {
    console.log(chalk.cyan.bold(`\n${cat.charAt(0).toUpperCase() + cat.slice(1)}:`));
    categories[cat].forEach(c => {
      console.log(`  ${chalk.green(c.name)} - ${chalk.gray(c.description.substring(0, 50))}...`);
    });
  });
  
  console.log(chalk.blue('\n\nUsage:'));
  console.log(chalk.gray('  npx uiverse add <component-name>'));
  console.log(chalk.gray('  npx uiverse add button --directory ./my-project'));
}

program
  .name('uiverse')
  .description('CLI tool to install UI-Verse components')
  .version('1.0.0');

program
  .command('add <component>')
  .description('Add a component to your project')
  .option('-d, --directory <path>', 'Target directory for installation', '.')
  .action(addComponent);

program
  .command('list')
  .description('List all available components')
  .action(listComponents);

program
  .command('init')
  .description('Initialize a new UI-Verse project')
  .action(async () => {
    const spinner = ora('Initializing project...').start();
    
    const targetDir = process.cwd();
    const dirs = ['components', 'css', 'js', 'assets'];
    
    for (const dir of dirs) {
      await fs.ensureDir(path.join(targetDir, dir));
    }
    
    await fs.writeFile(path.join(targetDir, 'index.html'), `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My UI-Verse Project</title>
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>
  <h1>Welcome to UI-Verse</h1>
  <!-- Add your components here -->
  <script src="js/main.js"></script>
</body>
</html>`);
    
    await fs.writeFile(path.join(targetDir, 'css', 'styles.css'), `/* UI-Verse Project Styles */
:root {
  --primary-color: #eb6835;
  --secondary-color: #6c5ce7;
  --background: #ffffff;
  --text-color: #333333;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--background);
  color: var(--text-color);
  line-height: 1.6;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}
`);
    
    await fs.writeFile(path.join(targetDir, 'js', 'main.js'), `// UI-Verse Project Main File
console.log('UI-Verse project initialized');

// Add your component logic here
`);
    
    await fs.writeFile(path.join(targetDir, 'README.md'), `# UI-Verse Project

Quick start:
\`\`\`bash
# Add components
npx uiverse add button
\`\`\`
`);
    
    spinner.succeed(chalk.green('Project initialized successfully!'));
    console.log(chalk.blue('\nProject structure created:'));
    console.log(chalk.gray('  - index.html'));
    console.log(chalk.gray('  - css/styles.css'));
    console.log(chalk.gray('  - js/main.js'));
    console.log(chalk.gray('  - components/'));
  });

program.parse(process.argv);